use_frameworks!

platform :ios, '10.0'

target 'SSInAppPurchaseManage_Example' do
  pod 'SSInAppPurchaseManage', :path => '../'

  target 'SSInAppPurchaseManage_Tests' do
    inherit! :search_paths

    
  end
end
